spring:
  application:
    name: common-redis
  redis:
    database: 1
    host: 106.14.150.87
    port: 6379
    jedis:
      pool:
        max-active: 200 #最大连接数
        max-wait: -1    #连接池最大等待时间（负数表示没有限制）
        max-idle: 10    #连接池最大空闲数
        min-idle: 0     #连接池最小空闲数
    timeout: 2000       #连接超时时间

server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://129.204.120.143:8761/eureka/

#配置缓存首页商品分类的key
frontend_catresult_redis_key: frontend:catresult:redis:key

#配置缓存首页大广告位的key
frontend_ad_redis_key: frontend:ad:redis:key:89

#配置缓存商品基本信息的key
frontend_item_basic_info_key: frontend:item:basic:info:key

#配置缓存商品描述的key
frontend_item_desc_key: frontend:item:desc:key

#配置缓存商品参数信息的key
frontend_item_param_item_key: frontend:item:param:item:key

#缓存用户的key
user_session_redis_key: user:session:redis:key

#缓存购物车的key
frontend_cart_redis_key: frontend:cart:redis:key

#缓存订单id的key
order_item_id_key: order:item:id:key

#订单id初始值
init_item_id: 2000