spring:
  application:
    name: frontend-order
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.150.87:3306/bz_shop?characterEncoding=UTF-8
    username: root
    password: Xiaopang88.
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9111

eureka:
  client:
    serviceUrl:
      defaultZone: http://129.204.120.143:8761/eureka/

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070