spring:
  application:
    name: frontend-portal

server:
  port: 9030

eureka:
  client:
    serviceUrl:
      defaultZone: http://129.204.120.143:8761/eureka/

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000